### ISSUE TITLE
Dont work right.

### ISSUE THREAD

**Issue by gabriel-logan** [rnheroes/react-native-toastable#10]
![image](https://github.com/rnheroes/react-native-toastable/assets/96627244/6b4a66e1-2d79-42ed-a87a-33d63c914eab)

![image](https://github.com/rnheroes/react-native-toastable/assets/96627244/bfbb1e23-23d3-497e-97fb-e2351ed547fb)

I've already tried involving it in a safeareaprovider, it doesn't work. I made it work without the offset, but when I click on show and hide several times at the same time, toast crashes and stays open forever.

**Comment by enestatli** [comment]
Hello, you have to wrap your whole app with SafeAreaProvider, I cannot see that in the attached images. If you are not sure how to do it, I can show you an example.

**Comment by gabriel-logan** [comment]
Show me please, then

**Comment by enestatli** [comment]
```
export default function RootNavigation() {
    const { top } = useSafeAreaInsets();

    return (
        <RootProvider>
            <NavigationContainer />
            <Toastable
                statusMap={{
                    success: 'red'
                    danger: 'yellow'
                    warning: 'green'
                    info: 'blue'
                }}
                offset={top}
                position="top"
            />
        </RootProvider>
    );
}

import { SafeAreaProvider } from 'react-native-safe-area-context';

export const RootProvider = ({ children }: PropsWithChildren) => (
    <SafeAreaProvider>
        { /* your other providers */ }
            {children}
    </SafeAreaProvider>
);

**Comment by gabriel-logan** [comment]
Ok, it works, I tested it with your settings, just a note, it is saving the state and not providing security in the rendering, if the user clicks several times to run the show toast, it saves the state and even if the user stops clicking it keeps spawning on the screen continuously.

Another thing, I tested it within redux saga and it didn't work, is there any way to make it work there?

**Comment by enestatli** [comment]
Can you show me the code? It should work within React context or outside.

It will be shown as much as user clicks the button. What's wrong with this?

**Comment by gabriel-logan** [comment]
I suggest you add a takeLatest, so if the user clicks several times, the component will only execute based on the last one, not causing an overload crash.

About redux, in a common redux, I tested it and it worked in react components, but trying to run it in the saga generator function, it simply wouldn't open. But anyway, I'm not using your lib anymore, thank you.
