### ISSUE TITLE
Is it possible to programmaticaly hide a toast ? 

### ISSUE THREAD

**Issue by AurelienBdl** [rnheroes/react-native-toastable#5]
I have a toast with the property "alwaysVisible" to true and would like to hide it programmaticaly. 

I am showing a "Internet lost" error toast when connection is lost and would like to remove the toast when connection is back.

**Comment by AurelienBdl** [comment]
Any update ?

**Comment by enestatli** [comment]
> Any update ?

I am planning to send a new release regarding the issue

**Comment by enestatli** [comment]
@AurelienBdl Thank you for the issue, now you can use hideToastable method, to hide the most current one.

**Comment by AurelBdl** [comment]
Hi again,

I couldn't see the hideToastable method in v.0.4.0 so i installed the version 0.3.0 but couldn't import it the same way as showToastable. Can you provide a small example ? 

Thanks in advance !

**Comment by AurelienBdl** [comment]
Hi again,

I couldn't see the hideToastable method in v.0.4.0 so i installed the version 0.3.0 but couldn't import it the same way as showToastable. Can you provide a small example ?

Thanks in advance !

**Comment by AurelienBdl** [comment]
> > Hi again,
> > I couldn't see the hideToastable method in v.0.4.0 so i installed the version 0.3.0 but couldn't import it the same way as showToastable. Can you provide a small example ?
> > Thanks in advance !
> 
> Thank you for letting me know, I forget to export the method globally, now you can import and use the method just like showToastable.
> 
> `import { hideToastable, showToastable } from 'react-native-toastable';`
> 
> https://github.com/rnheroes/react-native-toastable?tab=readme-ov-file#usage
> 
> Please upgrade to the latest version -> 0.4.1

Thanks a lot !
